In [1]:
import cv2

In [2]:
face_cascade=cv2.CascadeClassifier(r'images\haarcascade_frontalface_default.xml')

In [3]:
#img=cv2.imread(r'images\Rekha_in_2019.jpg')
#gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img=cv2.imread(r'images\images2.jpg')
#img=cv2.resize(img,(300,200))

In [4]:
faces=face_cascade.detectMultiScale(img)
print(faces)

[[ 21  54  45  45]
 [128  29  44  44]
 [234  27  46  46]]


In [5]:



for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),((x+w),(y+h)),(255,0,0),3)
    


In [6]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Eye Detection With OpenCV

'''detecMultiScale() function is for detecting objects if it finds a face in the image it will return 
in the form of x,y,w,h. and it needs some parameters.

ScaleFactor: This is parameter is for specifying  how much the image size is reduced at 
each image scale.

minNeighbors: Parameter specifying how many neighbors each candidate rectangle should have to
retain it, this parameter will affect the quality of the detected faces.'''

import cv2
 
 
 
image = cv2.imread(r'images\Rekha_in_2019.jpg')
eye_cascade = cv2.CascadeClassifier(r'images\haarcascade_eye.xml')
eyes = eye_cascade.detectMultiScale(image, scaleFactor = 1.1, minNeighbors = 5)
 
 
for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(image,(ex,ey),(ex+ew,ey+eh),(255,0,0),5)
 
 
 
cv2.imshow("Eye Detected", image)
 
 
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import cv2


In [2]:
face_cascade=cv2.CascadeClassifier(r'images\haarcascade_frontalface_default.xml')

In [3]:
cap=cv2.VideoCapture(0)
while True:
    ret,img=cap.read()
    faces=face_cascade.detectMultiScale(img)
    print(faces)
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),((x+w),(y+h)),(255,0,0),3)
    cv2.imshow('Image',img)
    if cv2.waitKey(0)==27 :
        break
        
cap.release()
cv2.destroyAllWindows()

()


In [4]:
import numpy as np
import cv2

face_cascade = cv2.CascadeClassifier(r'images\haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(r'images\haarcascade_eye.xml')
cap = cv2.VideoCapture(0)

while 1:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()





In [ ]:
'''
img = cv2.imread(r'images\images2.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for (x,y,w,h) in faces:
     cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
     roi_gray = gray[y:y+h, x:x+w]
     roi_color = img[y:y+h, x:x+w]
     eyes = eye_cascade.detectMultiScale(roi_gray)
     for (ex,ey,ew,eh) in eyes:
         cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()'''

In [ ]:
'''Algorithm :


The frame is captured and converted to grayscale.
Bilateral Filtering is applied to remove impurities.
Face is detected with the haarcascade.
The ROI (Region Of Image) of Face is fed to eye detection part of algorithm.
Eyes are detected and resulting list is passed to if-else contruct.
If the length of list is more than two, means that the eyes are there.
Else the program is marked to be eye blinked and restarted.'''

In [4]:
#All the imports go here
import numpy as np
import cv2

#Initializing the face and eye cascade classifiers from xml files
face_cascade = cv2.CascadeClassifier(r'images\haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(r'images\haarcascade_eye_tree_eyeglasses.xml')


  
#Variable store execution state
first_read = True
  
#Starting the video capture
cap = cv2.VideoCapture(0)
ret,img = cap.read()
  
while(ret):
    ret,img = cap.read()
    #Coverting the recorded image to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #Applying filter to remove impurities
    gray = cv2.bilateralFilter(gray,5,1,1)
  
    #Detecting the face for region of image to be fed to eye classifier
    faces = face_cascade.detectMultiScale(gray, 1.3, 5,minSize=(200,200))
    if(len(faces)>0):
        for (x,y,w,h) in faces:
            img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
  
            #roi_face is face which is input to eye classifier
            roi_face = gray[y:y+h,x:x+w]
            roi_face_clr = img[y:y+h,x:x+w]
            eyes = eye_cascade.detectMultiScale(roi_face,1.3,5,minSize=(50,50))
  
            #Examining the length of eyes object for eyes
            if(len(eyes)>=2):
                #Check if program is running for detection 
                if(first_read):
                    cv2.putText(img, 
                    "Eye detected press s to begin", 
                    (70,70),  
                    cv2.FONT_HERSHEY_PLAIN, 3,
                    (0,255,0),2)
                else:
                    cv2.putText(img, 
                    "Eyes open!", (70,70), 
                    cv2.FONT_HERSHEY_PLAIN, 2,
                    (255,255,255),2)
            else:
                if(first_read):
                    #To ensure if the eyes are present before starting
                    cv2.putText(img, 
                    "No eyes detected", (70,70),
                    cv2.FONT_HERSHEY_PLAIN, 3,
                    (0,0,255),2)
                else:
                    #This will print on console and restart the algorithm
                    print("Blink detected--------------")
                    cv2.waitKey(3000)
                    first_read=True
              
    else:
        cv2.putText(img,
        "No face detected",(100,100),
        cv2.FONT_HERSHEY_PLAIN, 3, 
        (0,255,0),2)
  
    #Controlling the algorithm with keys
    cv2.imshow('img',img)
    a = cv2.waitKey(1)
    if(a==ord('q')):
        break
    elif(a==ord('s') and first_read):
        #This will start the detection
        first_read = False
  
cap.release()
cv2.destroyAllWindows()

In [5]:
import cv2
 
 
 
image = cv2.imread(r'images\Rekha_in_2019.jpg')
eye_cascade = cv2.CascadeClassifier(r'images\haarcascade_eye.xml')
eyes = eye_cascade.detectMultiScale(image, scaleFactor = 1.1, minNeighbors = 5)
 
 
for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(image,(ex,ey),(ex+ew,ey+eh),(255,0,0),5)
 
 
 
cv2.imshow("Eye Detected", image)
 
 
 
cv2.waitKey(0)
cv2.destroyAllWindows()